# YAML
---
name: test-action
on: [push]
  branches: [ "main" ]
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: log
        run: echo "::set-output name=tag::$(git describe --tags --all)"
      - id: publish
        gh release create steps.log.outputs.tag ${{ github.repository }}.zip -R https://github.com/${{ github.repository }}
